### ISSUE TITLE
Adapt coverage testing to require 100% of all new code.

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#107]
I would not be opposed to explicitly ignoring coverage on wire cutting and EF modules and requiring 100% of everything else implicitly. I feel that much of wire cutting will be replaced by a qpd-based approach soon, and EF was never designed for unit testing anyway. EF is tested with a variety of molecules of different complexities and tested against their known ground state energies. We know the coverage is 85% and barring a large refactor of EF, that is likely where it will always remain.

**Comment by garrison** [comment]
I mentioned this somewhere -- I think in a private message to you -- but another option is to measure coverage two times in the tox workflow: one for the subset of code we expect to be at 100% coverage, and a second time for everything all together.  It's probably much more honest to use the second number as the number we report in the coverage badge in the README.
