### ISSUE TITLE
Configure Intersphinx to link to classes of dependencies' API docs

### ISSUE THREAD

**Issue by garrison** [Qiskit-Extensions/circuit-knitting-toolbox#215]
See https://docs.readthedocs.io/en/stable/guides/intersphinx.html

It seems that intersphinx is already used by some other Qiskit projects, including qiskit-experiments, qiskit-machine-learning, qiskit-nature, qiskit-optimization, qiskit-terra, and retworkx.

**Comment by caleb-johnson** [comment]
@garrison did #308 resolve this?

**Comment by garrison** [comment]
> @garrison did #308 resolve this?

It is the first step.  As a next step, @SaashaJoshi is doing an audit to make sure all the external class links actually work, rather than the few big ones that that PR got working (QuantumCircuit and PauliList).  (I _think_ every class has to be marked as `:external` at least once for it to be picked up, but Saasha will probably have a better understanding.)
