### ISSUE TITLE
Continue to address/suppress warnings from unit tests

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#279]
There are currently still some straggler warnings (14 of them) in our unit tests. Investigate whether any/all of these can be addressed.

**Comment by garrison** [comment]
It's best to pay attention to the "development version tests" to understand which warnings are still relevant.  For instance, https://github.com/Qiskit/qiskit-terra/pull/10308 fixed a few numpy-related warnings that we were seeing.
