### ISSUE TITLE
Support a wider variety of Qiskit gates for automatic, optimal decomposition

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#288]
Support a wider variety of Qiskit gates for automatic, optimal decomposition.

- [x] `DCXGate` (#294)
- [x] `CHGate` (#290)
- [x] `CPhaseGate` (#298)
- [x] `CSGate` (#298)
- [x] `CSdgGate` (#298)
- [x] `CSXGate` (#296)
- [x] `CYGate` (#290)
- [x] `ECRGate` (#292)
- [ ] `RZXGate` (support via KAK and test added in #302)
- [x] `SwapGate` (#294)
- [x] `iSwapGate` (#294)

**Comment by garrison** [comment]
Thanks, I hadn't thought it this yet.  I _think_ it would be relatively simple to add support for `ECRGate`.  We could add support for `RZXGate`, too, while we are at it.

**Comment by garrison** [comment]
Here's a list of gates that I _believe_ we could support pretty easily:

- [ ] `DCXGate`
- [ ] `CHGate`
- [ ] `CPhaseGate`
- [ ] `CSGate`
- [ ] `CSdgGate`
- [ ] `CSXGate`
- [ ] `CYGate`
- [ ] `ECRGate`
- [ ] `RZXGate`

Even if we eventually implement general unitaries (#186), having more gates may be useful once we figure out a way to implement adjusting parameters in reconstruction (#256).
