### ISSUE TITLE
Circuit cutting in a loop with a session

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#310]
Ensure the cutting API supports creation of an outer session, and that an iterative cutting routine can be run without losing the outer session. We also need to maintain compatibility with quantum serverless and ensure we can serialize all of inputs/outputs.

**Comment by garrison** [comment]
I don't think there's anything left for us to do here.  Since #404, it's now the user's job to handle the Qiskit primitives in their preferred way.  (Feel free to re-open if you disagree.)

**Comment by garrison** [comment]
> ensure we can serialize all of inputs/outputs

As for serialization, there is an open issue (#444) for serialization with qpy, but pickle serialization is most likely even better for use with Quantum Serverless.
