### ISSUE TITLE
CI doesn't find unused function args

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#319]
CI does not seem to pick up unused function arguments.

I had two unused arguments to circuit_knitting.forging.efknitter._estimate_expvals in #307, and the style checks passed. The unused args have since been removed, but this should have been caught in CI.

**Comment by caleb-johnson** [comment]
I think ruff should catch this but checking now

**Comment by garrison** [comment]
> I think ruff should catch this but checking now

If not, #146 should.
