### ISSUE TITLE
execute_experiments should not batch subcircuit experiments unless multiple samplers are passed

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#330]
Batching when only one `Sampler` is passed results in multiple consecutive jobs, and each job contains significant queuing and error mitigation overhead. We shouldn't batch unless the user has set the subcircuits up for different backends or with different sets of options.

**Comment by garrison** [comment]
It's not so much that batching _shouldn't_ be used, but rather that there should be just one big batch is there is only a single Sampler, right?

**Comment by caleb-johnson** [comment]
> It's not so much that batching _shouldn't_ be used, but rather that there should be just one big batch is there is only a single Sampler, right?

Yes, there is a significant cost to batching. If you're not using different options between the two batches, you may as well run all the experiments together and save yourself unnecessary queueing between batched subcircuit jobs. This will save you hours in non-reservation cases, especially if you're separating into several subcircuits.
