### ISSUE TITLE
Cutting decompose step should return a subexperiment dictionary

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#387]
For circuit cutting, users should have a way to map a subexperiment index (output from the decompose step) to the specific sample/sub-observable from which it was created. The sample could be represented in a number of ways -- maybe a list of (basis, id) tuples would be an intuitive representation of a "sample"?

**Comment by garrison** [comment]
This is a continuation of the conversation at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/378#discussion_r1309157716.

**Comment by caleb-johnson** [comment]
This issue is stale. Dictionaries are now used in cutting-for-width workflows.
