### ISSUE TITLE
What does `observables` mean in the function `partition_problem`?

### ISSUE THREAD

**Issue by sirgeorgesawcon** [Qiskit-Extensions/circuit-knitting-toolbox#490]
Following the first [gate cutting tutorial](https://qiskit-extensions.github.io/circuit-knitting-toolbox/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.html), 

This tutorial explains how you can replace non-local gates with local operations in the superoperator representations and effectively cut the gates, reducing the number of qubits required to run the circuit.

From the tutorial, I see they just make a random circuit :

![KbXsY](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/assets/63145298/c0920c0b-3e0d-411e-81bf-a3d1b838633a)

Then they want it to be cut into two subcircuits of two-qubit each and then they wrote the code:

```python
from qiskit.quantum_info import PauliList

observables = PauliList(["ZZII", "IZZI", "IIZZ", "XIXI", "ZIZZ", "IXIX"])
```

I don't understand the choice of these Pauli matrices, the order in which they are, and the fashion they are chosen.

When I look at the [source code](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/b7e27acb16d9197ba50ed855e7cb19f3485de799/circuit_knitting/cutting/cutting_decomposition.py#L141) for the function:

It says, 
`If provided, ``observables`` will be separated along the boundaries specified by
    the partition labels.`

and

`observables: The observables to separate`

I see that you can give `None` as observables and it still cut, but then it doesn't generate the subexperiments to run on backend, since it asks for `observables`.

How does this choice of observable make sense with this circuit? and if I chose to cut a different circuit, how will my `observables` change?

**Comment by caleb-johnson** [comment]
> How does this choice of observable make sense with this circuit? and if I chose to cut a different circuit, how will my `observables` change?

The choice of observable and circuit is really arbitrary here. We just want to demonstrate how one would partition a circuit and observable in this cutting framework.

> I see that you can give `None` as observables and it still cut, but then it doesn't generate the subexperiments to run on backend, since it asks for `observables`.
> 
If `None` is passed as the `observables` arg, we will just cut the circuit only, and it would be up to the user to specify their observables manually. If observables and circuits, both acting on `N` qubits, are passed. They will both be separated between the same qubit boundaries (if the circuit is separable after cutting), and the subcircuits and subobservables for each partition qubit will be returned together in a dictionary.

**Comment by sirgeorgesawcon** [comment]
Thanks for explaining it.
