### ISSUE TITLE
Remove uses of `ibmq_qasm_simulator` from cutqc tutorials

### ISSUE THREAD

**Issue by garrison** [Qiskit-Extensions/circuit-knitting-toolbox#502]
Cloud simulators are being retired: https://docs.quantum.ibm.com/announcements/product-updates/2024-03-22-announcement-cloud-simulators-and-lab

**Comment by garrison** [comment]
I think the most logical thing to do is replace mentions of `"ibmq_qasm_simulator"` with `service.least_busy().name`.

**Comment by caleb-johnson** [comment]
> I think the most logical thing to do is replace mentions of `"ibmq_qasm_simulator"` with `service.least_busy().name`. (also make sure to update any comments that mention "qasm simulator")

Can we punt this until we remove cutQC or are things going to break before the removal release?

**Comment by garrison** [comment]
>Can we punt this until we remove cutQC or are things going to break before the removal release?

Cloud simulators are due to be retired on May 15: https://docs.quantum.ibm.com/announcements/product-updates/2024-03-22-announcement-cloud-simulators-and-lab

so it'd be nice to just take care of this in the quickest/easiest way possible before then.
