### ISSUE TITLE
Update all notebooks to reflect IQP style circuits

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#524]

**Comment by garrison** [comment]
What do you mean by IQP circuits?  I think you are talking about something other than https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.IQP but can't figure out what.

**Comment by caleb-johnson** [comment]
> What do you mean by IQP circuits? I think you are talking about something other than https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.IQP but can't figure out what.

Sorry bout that, the default style for QuantumCircuit.draw() is "iqp" now :). Our `main` branch tutorials have the old style.

**Comment by garrison** [comment]
> > What do you mean by IQP circuits? I think you are talking about something other than https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.IQP but can't figure out what.
> 
> Sorry bout that, the default style for QuantumCircuit.draw() is "iqp" now :). Our `main` branch tutorials have the old style.

Got it; this was actually my second suspicion, but then I mistakenly convinced myself that that style was known as "iqx". In fact, I grepped for "iqx" and found [this line](https://github.com/Qiskit/qiskit/blob/4f7b54a6e7b9c2ea549cf55eeac5db21091b3802/qiskit/visualization/circuit/styles/iqp-dark.json#L2) is a file named `iqp-dark.json`, among others :laughing:
