### ISSUE TITLE
Merge PRs associated with v0.8.0 to main

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#600]
Merge all PRs associated with v0.8.0 release.

- [ ] Create a branch `stable/0.8-ckt` after everything is merged to `main` and before closing this issue

**Comment by garrison** [comment]
I created a `stable/0.8` branch, which forked from `stable/0.7` instead of `main` so it would be as much like 0.7 as possible.  Calling this one done.
