### ISSUE TITLE
Accept both strings and Backends for the backend field in EFGSSolver

### ISSUE THREAD

**Issue by caleb-johnson** [Qiskit-Extensions/circuit-knitting-toolbox#62]
Currently, entanglement forging only accepts strings for backends. It should accept both strings and Backends

**Comment by garrison** [comment]
If passed a `Backend`, I assume the plan is to use it to construct a `BackendEstimator`?

**Comment by caleb-johnson** [comment]
> If passed a `Backend`, I assume the plan is to use it to construct a `BackendEstimator`?

I haven't looked closely at this class yet, and I also haven't thought about exact implementation. At a quick glance, this looks like exactly what we should use!

Thanks

**Comment by caleb-johnson** [comment]
Stale issue. Closing.
